/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Millow
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/LogosIMG/LogoWachi.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        pswUser = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BtnMenu = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BtnEntrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JButton();
        BtnMini = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(236, 252, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(236, 252, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("I.P.S Wachitroco");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 53, 215, 35));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tu salud es mi compromiso, mi prioridad,");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 106, 344, 28));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("!Bienvenido¡ Por favor, ingrese su cuenta.");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 306, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("INICIAR SESION");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("somos tu mejor opcion.");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuario");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtUser.setBackground(new java.awt.Color(236, 252, 255));
        txtUser.setText("name");
        txtUser.setBorder(null);
        jPanel4.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 270, 30));

        pswUser.setBackground(new java.awt.Color(236, 252, 255));
        pswUser.setText("jPasswordField1");
        pswUser.setBorder(null);
        jPanel4.add(pswUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 270, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 270, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 10));

        BtnMenu.setBackground(new java.awt.Color(236, 252, 255));
        BtnMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnMenu.setForeground(new java.awt.Color(0, 0, 0));
        BtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogosIMG/logout_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        BtnMenu.setBorder(null);
        BtnMenu.setBorderPainted(false);
        BtnMenu.setContentAreaFilled(false);
        BtnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMenu.setFocusPainted(false);
        jPanel4.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jPanel5.setBackground(new java.awt.Color(178, 252, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(75, 24));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEntrar.setBackground(new java.awt.Color(178, 252, 255));
        BtnEntrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnEntrar.setText("ENTRAR");
        BtnEntrar.setBorder(null);
        BtnEntrar.setBorderPainted(false);
        BtnEntrar.setContentAreaFilled(false);
        BtnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEntrar.setFocusPainted(false);
        jPanel5.add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 130, 60));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        jPanel3.setBackground(new java.awt.Color(178, 252, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogosIMG/logAdmin.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 182, -1, -1));

        jPanel6.setBackground(new java.awt.Color(236, 252, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setBackground(new java.awt.Color(236, 252, 255));
        BtnCerrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogosIMG/close_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        BtnCerrar.setBorder(null);
        BtnCerrar.setBorderPainted(false);
        BtnCerrar.setContentAreaFilled(false);
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.setFocusPainted(false);
        jPanel6.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 50, 40));

        BtnMini.setBackground(new java.awt.Color(236, 252, 255));
        BtnMini.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnMini.setForeground(new java.awt.Color(0, 0, 0));
        BtnMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogosIMG/remove_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        BtnMini.setBorder(null);
        BtnMini.setBorderPainted(false);
        BtnMini.setContentAreaFilled(false);
        BtnMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMini.setFocusPainted(false);
        BtnMini.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(BtnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 370, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCerrar;
    public javax.swing.JButton BtnEntrar;
    public javax.swing.JButton BtnMenu;
    public javax.swing.JButton BtnMini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPasswordField pswUser;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
