/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.ImageIcon;




/**
 *
 * @author Millow
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/LogosIMG/LogoWachi.png")).getImage());
    }
    
    
     // Icono
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        load = new javax.swing.JProgressBar();
        textLoad = new javax.swing.JLabel();
        mmisj = new javax.swing.JLabel();
        numLoad = new javax.swing.JLabel();
        imgSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 190, 10));

        textLoad.setBackground(new java.awt.Color(0, 0, 0));
        textLoad.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        textLoad.setForeground(new java.awt.Color(0, 0, 0));
        textLoad.setText("loading...");
        jPanel1.add(textLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 140, 30));

        mmisj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogosIMG/MMISJ.png"))); // NOI18N
        jPanel1.add(mmisj, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 170, 170));

        numLoad.setBackground(new java.awt.Color(0, 0, 0));
        numLoad.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        numLoad.setForeground(new java.awt.Color(0, 0, 0));
        numLoad.setText("    0 %");
        numLoad.setToolTipText("");
        numLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(numLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 40, 20));

        imgSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/I.P.S.png"))); // NOI18N
        jPanel1.add(imgSplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgSplash;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar load;
    private javax.swing.JLabel mmisj;
    public javax.swing.JLabel numLoad;
    public javax.swing.JLabel textLoad;
    // End of variables declaration//GEN-END:variables
}
